messaging:
  host: mq.gbif.org
  virtualHost: /crawler/dev
  username: crawler
  password: crawler
registry:
  wsUrl: http://b11g9.gbif.org:8080/registry-ws
  user: markus
  password: markus
queueName: metasync
threadCount: 30
