messaging:
  host: mq.gbif.org
  virtualHost: /production
  username: crawler
  password: crawler
registry:
  wsUrl: http://jawa.gbif.org:8080/b_registry-ws
  user: crawler.gbif.org
  password: A3z3]w]%9M?426UN
queueName: xml-metasync
threadCount: 30
