wsUrl: http://crawler.gbif.org:8080/crawler-ws
registry:
  wsUrl: http://jawa.gbif.org:8080/b_registry-ws
  user: crawler.gbif.org
  password: A3z3]w]%9M?426UN 
zooKeeper:
  connectionString: c1n8.gbif.org,c1n9.gbif.org,c1n10.gbif.org
  namespace: crawler
archiveDirectory: /home/crap/storage/results
