wsUrl: http://b11g9.gbif.org:8080/crawler-ws
registry:
  wsUrl: http://b11g9.gbif.org:8080/registry-ws
  user: markus
  password: markus
zooKeeper:
  connectionString: c1n8.gbif.org,c1n9.gbif.org,c1n10.gbif.org
  namespace: crawler
archiveDirectory: /home/crap/storage/results
