messaging:
  host: mq.gbif.org
  virtualHost: /crawler/dev
  username: crawler
  password: crawler
zooKeeper:
  connectionString: c1n8.gbif.org,c1n9.gbif.org,c1n10.gbif.org
  namespace: crawler
poolSize: 50
queueName: xml-fragmenter
crawlerWsUrl: http://b11g9.gbif.org:8080/crawler-ws/
