queueName: metrics_dataset_taxon_cube
cubeTable: prepop_crawler_dataset_taxon_cube
columnFamily: dc
writeBatchSize: 1000
poolSize: 50
hbaseConfig: /home/crap/config/hbase-site.xml
messaging:
  host: mq.gbif.org
  virtualHost: /crawler/dev
  username: metrics
  password: metrics
