###
## Concurrent writing improves throughput to HBase significantly.
## 
## The message consumers are thread safe but will lock each other, thus consumer threads > 1 makes little sense. 
##
####
hbaseConfig: /home/crap/config/hbase-site.xml
messaging:
  host: mq.gbif.org
  virtualHost: /crawler/dev
  username: metrics
  password: metrics
cubeTable: prepop_crawler_maps_cube
columnFamily: dc
messageConsumerThreads: 1
batchSize: 10000
batchFlushThreads: 10
pixelsPerCluster: 1