updatesQueueName: occurrence_index_updates
deletionsQueueName: occurrence_index_deletions
commitWithinMs: 30000
poolSize: 10
solrServer: http://b11g9.gbif.org:8081/crawler-occurrence-solr/
messaging:
  host: mq.gbif.org
  virtualHost: /crawler/dev
  username: processor
  password: processor
ganglia:
  gangliaHost: b5g2.gbif.org
  gangliaPort: 8649
