messaging:
  host: mq.gbif.org
  virtualHost: /crawler/dev
  username: processor
  password: processor
zooKeeper:
  connectionString: c1n8.gbif.org,c1n9.gbif.org,c1n10.gbif.org
  namespace: crawler
ganglia:
  gangliaHost: b5g2.gbif.org
  gangliaPort: 8649
msgPoolSize: 50
hbasePoolSize: 50
queueName: occurrence_interp
occTable: crawler_occurrence
counterTable: crawler_occurrence_counter
lookupTable: crawler_occurrence_lookup
