messaging:
  host: mq.gbif.org
  virtualHost: /production
  username: registry-change
  password: registry-change
registryChangeQueueName: registry-change
registryWsUrl: http://jawa.gbif.org:8080/b_registry-ws
